---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        args: ["--print-width=135"]
  - repo: https://github.com/ansible/ansible-lint
    rev: v5.3.1
    hooks:
      - id: ansible-lint
        files: '\.ya?ml$'
        args: ["-vv", "--show-relpath"]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: ["--ignore-case", "--unique"]
        files: '^\.gitignore$'
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.3
    hooks:
      - id: shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        exclude_types: [makefile]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: 3df2cd5fc0bffe63b0a5e0021f9885a223d51600
    hooks:
      - id: remove-unicode-zero-width-space
      - id: remove-en-dashes
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
