---
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        files: '\.ya?ml$'
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: .gitignore
      - id: mixed-line-ending
        args: ['--fix=lf' ]
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-tabs
        exclude_types: [makefile]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
      - id: yamllint
  - repo: https://github.com/kadrach/pre-commit-gitlabci-lint
    rev: ab984c60414b012e294a65166691473047ccce49
    hooks:
      - id: gitlabci-lint
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: fdcede7a5c8ea762c903f242279112161cf35d9f
    hooks:
      - id: CVE-2017-18342
      - id: remove-unicode-zero-width-space
      - id: remove-en-dashes
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
