---
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf' ]
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: remove-tabs
        exclude_types: [makefile]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.20.0
    hooks:
      - id: yamllint
  - repo: https://github.com/kadrach/pre-commit-gitlabci-lint
    rev: ab984c60414b012e294a65166691473047ccce49
    hooks:
      - id: gitlabci-lint
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: d0ec497c80183b0e8b19216154c26a956103a416
    hooks:
      - id: CVE-2017-18342
      - id: remove-en-dashes
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
      - id: sort-gitignore
