[tool.poetry]
name = "exiftool"
version = "0.2.1"
description = "Role to install ExifTool."
authors = ["Thomas Lehoux, Daniel Hoherd"]

[tool.poetry.dependencies]
python = "^3.9.0"
ansible = "^2.10.7"
pre-commit = "^2.15.0"
pytest = "^6.2.5"
molecule = "^3.5.2"
docker = "^5.0.3"
molecule-docker = "^1.1.0"
pytest-testinfra = "^6.4.0"

[tool.black]
line-length = 132
target-version = ['py39']
include = '\.pyi?$'
exclude = '(venv|.vscode)'

[build-system]
requires = ["poetry>=1.1.11"]
build-backend = "poetry.masonry.api"
