---
# tasks file for danielhoherd.exiftool
- name: test if exiftool is already installed
  register: out
  ansible.builtin.command: exiftool -Ver
  ignore_errors: yes
  changed_when: False

- name: "Set version fact"
  set_fact:
    installed_version: "{{ out.stdout }}"
  when: out.rc == 0

- block:
    - name: set exiftool checksum
      set_fact:
        exiftool_checksum: "sha1:{{ exiftool_checksums[exiftool_version] }}"
      when:
        - exiftool_verify_checksum | bool
        - exiftool_checksum is not defined
        - exiftool_version in exiftool_checksums
        - ansible_version.major >= 2

    - name: download exiftool archive
      get_url:
        url: https://exiftool.org/Image-ExifTool-{{ exiftool_version }}.tar.gz
        dest: /tmp
        checksum: "{{ exiftool_checksum|default(omit) }}"

    - name: unarchive exiftool archive
      unarchive:
        src: "/tmp/Image-ExifTool-{{ exiftool_version }}.tar.gz"
        mode: 0644
        dest: /tmp
        copy: no

    - name: install exiftool
      ansible.builtin.shell: perl Makefile.PL && make test && make install
      args:
        chdir: "/tmp/Image-ExifTool-{{ exiftool_version }}/"
      become: true

    - name: remove tmp files
      file:
        path: "/tmp/Image-ExifTool-{{ exiftool_version }}.tar.gz"
        state: absent
        recurse: no
      become: true
  when: ( installed_version | default('0.0.1') ) is not version(exiftool_version, '==')
