---
# tasks file for danielhoherd.exiftool
- name: Test if exiftool is already installed
  register: out
  command: exiftool -ver
  ignore_errors: yes
  changed_when: False

- name: "Set version fact"
  set_fact:
    installed_version: "{{ out.stdout }}"
  when: out.rc == 0

- name: "Download and install exiftool"
  when: ( installed_version | default('0.0.1') ) is not version(exiftool_version, '==')
  block:
    - name: Set exiftool checksum
      set_fact:
        exiftool_checksum: "sha1:{{ exiftool_checksums[exiftool_version] }}"
      when:
        - exiftool_checksum is not defined
        - exiftool_version in exiftool_checksums
        - ansible_version.major >= 2

    - name: Download exiftool archive
      get_url:
        url: "https://exiftool.org/Image-ExifTool-{{ exiftool_version }}.tar.gz"
        dest: /tmp
        mode: 0644
        checksum: "{{ exiftool_checksum | default(omit) }}"

    - name: Unarchive exiftool archive
      unarchive:
        src: "/tmp/Image-ExifTool-{{ exiftool_version }}.tar.gz"
        mode: 0644
        dest: /tmp
        copy: no

    - name: Install exiftool
      shell: perl Makefile.PL && make test && make install
      args:
        chdir: "/tmp/Image-ExifTool-{{ exiftool_version }}/"
      become: true
      changed_when: true

    - name: Remove tmp files
      file:
        path: "/tmp/Image-ExifTool-{{ exiftool_version }}.tar.gz"
        state: absent
        recurse: no
      become: true
