---
scenario:
  name: focal
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:xenial
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
  config_options:
    defaults:
      stdout_callback: yaml
      callback_whitelist: profile_roles, profile_tasks
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    s: yes
    # drop 'molecule verify' to pdb on failure - https://github.com/ansible-community/molecule/issues/2968#issuecomment-851609271
    # pdb: true
  lint:
    name: flake8
